version: '2'

services:
  searxng:
    image: 'searxng/searxng:${SEARXNG_IMAGE_VERSION:-latest}'
    depends_on:
      - 'searxng-redis'
    environment:
      IMAGE_PROXY: 'true'
      LIMITER: 'true'
      REDIS_URL: 'redis://searxng-redis:6379/0'
      SEARXNG_BASE_URL: 'https://searx.${SITE:-localhost}/'
    healthcheck:
      test: ['CMD',
             'wget', '-q', '--spider', '--proxy=off', 'localhost:8080/healthz']
    labels:
      traefik.enable: true
      traefik.http.routers.searxng.rule: 'Host(`searx.${SITE:-localhost}`)'
      traefik.http.services.searxng.loadbalancer.server.port: 8080
    networks:
      - 'traefik-network'
    restart: 'always'
    volumes:
      - './searxng/:/etc/searxng:rw'

  searxng-redis:
    image: 'redis:6.0-alpine'
    command: 'redis-server --save "" --appendonly "no"'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    labels:
      traefik.enable: false
    networks:
      - 'traefik-network'
    restart: 'always'
    tmpfs:
      - '/var/lib/redis'
networks:
  traefik-network:
    external: true