---
- name: Ensure immich Docker Compose directory exists
  file:
    path: "{{ docker_projects_path }}/immich"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Check if .env file exists
  stat:
    path: "{{ docker_projects_path }}/immich/.env"
  register: env_file_check

- name: Generate .env file for immich
  template:
    src: .env.j2
    dest: "{{ docker_projects_path }}/immich/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: not env_file_check.stat.exists

- name: Copy immich Docker Compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_projects_path }}/immich/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Launch immich with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ docker_projects_path }}/immich"
    state: present
    pull: yes
    recreate: smart
    remove_orphans: yes
