- name: Manage Immich Docker Compose Project
  hosts: docker_host
  become: true
  vars_files:
    - ../group_vars/all.yaml

  tasks:
    - name: Ensure Docker and Docker Compose are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest images
      ansible.builtin.command:
        cmd: "docker compose pull"
        chdir: "{{ immich_path }}"
      when: update_service | default(false)

    - name: Start Immichs services
      ansible.builtin.command:
        cmd: "docker compose up -d"
        chdir: "{{ immich_path }}"

    - name: Stop Immich services
      ansible.builtin.command:
        cmd: "docker compose down"
        chdir: "{{ immich_path }}"
      when: stop_service | default(false)
