- name: Manage Worpress Docker Compose Services
  hosts: docker_host
  become: true
  vars_files:
    - ../group_vars/all.yaml

  tasks:
    - name: Ensure Docker and dependencies are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose-plugin
        - python3-docker
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Wordpress with Docker Compose
      community.docker.docker_compose:
        project_src: "{{ wordpress_path }}"
        pull: yes
        build: no
        state: present
        restarted: "{{ update_service | default(false) }}"
      register: compose_result

    - name: Stop Wordpress services
      community.docker.docker_compose:
        project_src: "{{ wordpress_path }}"
        state: absent
      when: stop_service | default(false)

    - name: Display Compose Status
      ansible.builtin.debug:
        var: compose_result
